INSERT INTO `soil` (`symbol`, `description`, `category`)
VALUES
  ('AMA', 'ALMA', ''),
  ('AWG', 'AWANG', ''),
  ('APK', 'APEK', 'Aluvium Sungai Terbaru'),
  ('ASN (AHN)', 'ASAHAN', ''),
  ('AST', 'ALOR SEMAT', ''),
  ('BDK', 'BADAK', ''),
  ('BGG', 'BAGING', ''),
  ('BKU', 'BAKAU', ''),
  ('BKG', 'BAKONG', ''),
  ('BPU', 'BALIK PULAU', ''),
  ('BLG', 'BALING', ''),
  ('BNR', 'BANAR', ''),
  ('BGL', 'BANGGOL', ''),
  ('BJR', 'BANJAR', ''),
  ('BTL', 'BANTAL', ''),
  ('BMU', 'BATANG MERBAU', ''),
  ('BAM', 'BATU ANAM', ''),
  ('BHM', 'BATU HITAM', ''),
  ('BLN', 'BATU LAPAN', ''),
  ('BYS', 'BAYAS', ''),
  ('BDG', 'BELADING', ''),
  ('BBN', 'BEMBAN', ''),
  ('BTA', 'BENTA', ''),
  ('BEH', 'BEOH', ''),
  ('BRA', 'BERA', ''),
  ('BNM', 'BEMAM', ''),
  ('BTM', 'BERTAM', ''),
  ('BSH', 'BESERAH', ''),
  ('BJI', 'BINJAI', ''),
  ('BRH', 'BRIAH', ''),
  ('BAL', 'BUKIT AJIL', ''),
  ('BTG', 'BUKIT TEMIANG', ''),
  ('BTU', 'BUKIT TUKU', ''),
  ('BGR', 'BUNGOR', ''),
  ('BRG', 'BURONG', ''),
  ('BKI', 'BAKRI', ''),
  ('BCG', 'BERINCHANG', ''),
  ('BRT', 'BERUIT', ''),
  ('CRY', 'CAREY', ''),
  ('CMN', 'CERMIN', ''),
  ('CLI', 'CHALLI', ''),
  ('CLK', 'CHANGKAT LOBAK', ''),
  ('CHT', 'CHAT', ''),
  ('CPA', 'CHEMPAKA', ''),
  ('CNM', 'CHENAAM', ''),
  ('CRG', 'CHENERING', ''),
  ('CGL', 'CHENGAL', ''),
  ('CHN(CNN)', 'CHENIAN', ''),
  ('CHS', 'CHERANG HANGUS', ''),
  ('CTG', 'CHERATING', ''),
  ('CLN', 'CHUNGLOON', ''),
  ('CKI', 'CUKAI', ''),
  ('CPG', 'CUPING', ''),
  ('DMK', 'DAMAK', ''),
  ('DPR', 'DAMPAR', ''),
  ('DRN', 'DURIAN', ''),
  ('FRI', 'FIKRI', ''),
  ('GAG', 'GADING', ''),
  ('GMI', 'GAJAH MATI', ''),
  ('GLI', 'GALI', ''),
  ('GOH', 'GOH', ''),
  ('GOL', 'GOL', ''),
  ('GCK', 'GONG CHENAK', ''),
  ('GUR', 'GUAR', ''),
  ('GGT', 'GUGUT', ''),
  ('GDG', 'GUNDANG', ''),
  ('HLU', 'HALU', ''),
  ('HRD', 'HARAD', ''),
  ('HMU', 'HARIMAU', ''),
  ('HYD', 'HOLYROD', ''),
  ('HTN', 'HUTAN', ''),
  ('IBI', 'IBAI', ''),
  ('IBK', 'IBOK', ''),
  ('IDS', 'IDRIS', ''),
  ('JBL', 'JABIL', ''),
  ('JBR', 'JABOR', ''),
  ('JBU', 'JAMBU', ''),
  ('JAN', 'JAN', ''),
  ('JWA', 'JAWA', ''),
  ('JYA', 'JAYA', ''),
  ('JTG', 'JELUTONG', ''),
  ('JPL', 'JEMPOL', ''),
  ('JRM', 'JERAM', ''),
  ('JRA', 'JERANGAU', ''),
  ('JTT', 'JERANTUT', ''),
  ('JNH', 'JEMEH', ''),
  ('JTA', 'JITRA', ''),
  ('JNG', 'JONG', ''),
  ('JRU', 'JURU', ''),
  ('KBU', 'KABU', ''),
  ('KBT', 'KAKI BUKIT', ''),
  ('KKM', 'KAMPONG KOLAM', ''),
  ('KPU', 'KAMPUNG PUSU', ''),
  ('KGR', 'KANGAR', ''),
  ('KGG', 'KANGKONG', ''),
  ('KSH', 'KASAH', ''),
  ('KTG', 'KATONG', ''),
  ('KWH', 'KAWAH', ''),
  ('KWG', 'KAWANG', ''),
  ('KYA', 'KAYA', ''),
  ('KYN', 'KAYAN', ''),
  ('KMG', 'KEMUNING', ''),
  ('KPG', 'KEPAYANG', ''),
  ('KRT', 'KERAIT', ''),
  ('KRK', 'KERAK', ''),
  ('KCI', 'KECHAI', ''),
  ('KCR', 'KECHOR', ''),
  ('KDH', 'KEDAH', ''),
  ('KKA', 'KEKURA', ''),
  ('KLU', 'KELAU', ''),
  ('KLG', 'KELEDANG', ''),
  ('KEM(KEG)', 'KEM', ''),
  ('KHG', 'KEMAHANG', ''),
  ('KMG', 'KEMANG', ''),
  ('KSL', 'KEMASUL', ''),
  ('KNG', 'KENING', ''),
  ('KYG', 'KERAYONG', ''),
  ('KPH', 'KERPAH', ''),
  ('KPI', 'KERPAI', ''),
  ('KPG', 'KERPANG', ''),
  ('KLS', 'KG. PERLIS', ''),
  ('KLN', 'KILAN', ''),
  ('KIN', 'KILIN', ''),
  ('KOL', 'KIOL', ''),
  ('KDG', 'KODIANG', ''),
  ('KOH', 'KOH', ''),
  ('KML', 'KOMEL', ''),
  ('KJI', 'KRANJI', ''),
  ('KUH', 'KUAH', ''),
  ('KBG', 'KUALA BRANG', ''),
  ('KKH', 'KUALA KEDAH', ''),
  ('KPS', 'KUALA PERLIS', ''),
  ('KTN', 'KUANTAN', ''),
  ('KUA', 'KUAU', ''),
  ('KLI', 'KULAI', ''),
  ('KLM', 'KULIM', ''),
  ('KUM', 'KUMBANG', ''),
  ('KDR', 'KUNDOR', ''),
  ('LKA', 'LAKA', ''),
  ('LLT', 'LALAT', ''),
  ('LBK', 'LAMBAK', ''),
  ('LAS', 'LANAS', ''),
  ('LCG', 'LANCHANG', ''),
  ('LWI', 'LANGKAWI', ''),
  ('LTG', 'LATING', ''),
  ('LKR', 'LEKIR', ''),
  ('LKK', 'LEKOK', ''),
  ('LNU', 'LINAU', ''),
  ('LGI', 'LINGGI', ''),
  ('LNG', 'LINTANG', ''),
  ('LAA', 'LOCAL ALLUVIUM ASSOCIATION', ''),
  ('LAC', 'LOCAL ALLUVIUM COMPLEX', ''),
  ('LYG', 'LOK YANG', ''),
  ('LSG', 'LUBOK SENDANG', ''),
  ('LIK', 'LUBUK ITIK', ''),
  ('LKT', 'LUBUK KIAT', ''),
  ('LNS', 'LUNAS', ''),
  ('LDG', 'LUNDANG', ''),
  ('MCA', 'MALACCA', ''),
  ('MLU', 'MALAU', ''),
  ('MKK', 'MANGKOK', ''),
  ('MNK', 'MANIK', ''),
  ('MRG', 'MARANG', ''),
  ('MRS', 'MARAS', ''),
  ('MRH', 'MAROH', ''),
  ('MSI', 'MASAI', ''),
  ('MLG', 'MAT DALING', ''),
  ('MDG', 'MEDANG', ''),
  ('MWI', 'MELAWI', ''),
  ('MPH', 'MERAPOH', ''),
  ('MBK', 'MERBOK', ''),
  ('MCG', 'MERCHANG', ''),
  ('MMH', 'MERHAMAH', ''),
  ('MKH', 'MUKAH', ''),
  ('MUN', 'MUNCHONG', ''),
  ('MSG', 'MUSANG', ''),
  ('NMI', 'NAMI', ''),
  ('NKA', 'NANGKA', ''),
  ('NPI', 'NAPAI', ''),
  ('NRG', 'NERANG', ''),
  ('NRS', 'NERUS', ''),
  ('NBG', 'NIBONG', ''),
  ('NPS', 'NIPIS', ''),
  ('PBR', 'PADANG BESAR', ''),
  ('PGI', 'PAGI', ''),
  ('PKG', 'PAK BONG', ''),
  ('PBK', 'PARIT BOTAK', ''),
  ('PPH', 'PASIR PUTEH', ''),
  ('PUH', 'PAUH', ''),
  ('PTG', 'PATANG', ''),
  ('PDU', 'PEDU', ''),
  ('PDK', 'PELANDUK', ''),
  ('PLH', 'PELEPAH', ''),
  ('PTL', 'PEMATANG TIMBUL', ''),
  ('PGA', 'PENAGA', ''),
  ('PBG', 'PENAMBANG', ''),
  ('PGG', 'PENGARANG', ''),
  ('PNR', 'PENOR', ''),
  ('PYG', 'PENYABONG', ''),
  ('PPT', 'PEREPAT', ''),
  ('PMG', 'PERMATANG', ''),
  ('PST', 'PERSIT', ''),
  ('PDG', 'PIANDANG', ''),
  ('PHI', 'POHOI', ''),
  ('PSA', 'POKOK SENA', ''),
  ('PRG', 'PRANG', ''),
  ('RGM', 'RENGAM', ''),
  ('RTU', 'RANTAU', ''),
  ('RSU', 'RASAU', ''),
  ('RTI', 'RHU TAPAI', ''),
  ('RLT', 'RINGLET', ''),
  ('RVA', 'RIVERINE ASSOCIATION', ''),
  ('RPN', 'ROMPIN', ''),
  ('RTN', 'ROTAN', ''),
  ('RDU(RDA)', 'RUDUA', ''),
  ('(RLA)RSL', 'RUSILA', ''),
  ('SGU', 'SAGU', ''),
  ('SNG', 'SENENG', ''),
  ('SLH', 'SALLEH', ''),
  ('SAT', 'SAT', ''),
  ('SBG', 'SEBERANG', ''),
  ('SKA', 'SEDAKA', ''),
  ('SDU', 'SEDU', ''),
  ('SGT', 'SEGAMAT', ''),
  ('SRI', 'SEGARI', ''),
  ('SCB', 'SEJACOB', ''),
  ('SLR', 'SELANGOR', ''),
  ('SKT', 'SELINGKAT', ''),
  ('SRN', 'SEMBRIN', ''),
  ('SNI', 'SENAI', ''),
  ('SRA', 'SENGGORA', ''),
  ('SYG', 'SEPAYANG', ''),
  ('SDG', 'SERDANG', ''),
  ('SBN', 'SEREMBAN', ''),
  ('SKM', 'SERKAM', ''),
  ('SKT', 'SERKAT', ''),
  ('SRK', 'SEROK', ''),
  ('SRG', 'SERONG', ''),
  ('STL', 'SETOL', ''),
  ('SMI', 'SG. MERANTI', ''),
  ('SPH', 'SIMPAH', ''),
  ('SWN', 'SITIAWAN', ''),
  ('SMA', 'SOGOMANA', ''),
  ('SUG', 'SUBANG', ''),
  ('SGI', 'SUNGAI', ''),
  ('SAN', 'SUNGAI ANAM', ''),
  ('SBH', 'SUNGAI BULOH', ''),
  ('SMS', 'SUNGAI MAS', ''),
  ('TTK', 'TAI TAK', ''),
  ('TGA', 'TANGGA', ''),
  ('TBN', 'TAMBUN', ''),
  ('TPN', 'TAMPIN', ''),
  ('TPI', 'TAMPOI', ''),
  ('TRA', 'TANAH RATA', ''),
  ('TDK', 'TANDAK', ''),
  ('TGG', 'TANGGANG', ''),
  ('TSK', 'TASIK', ''),
  ('TVY', 'TAVY', ''),
  ('TWR', 'TAWAR', ''),
  ('TGU', 'TEBENGAU', ''),
  ('TRU', 'TEBERAU', ''),
  ('TBK', 'TEBOK', ''),
  ('TEN', 'TEBUAN', ''),
  ('TGA', 'TELAGA', ''),
  ('TLG', 'TELANG', ''),
  ('TMG', 'TELEMONG', ''),
  ('TLK', 'TELOK', ''),
  ('TBH', 'TELUK BULUH', ''),
  ('TBA', 'TEMBAGA', ''),
  ('TBG', 'TEMBELING', ''),
  ('TBL', 'TEMBIL', ''),
  ('TLH', 'TEMERLOH', ''),
  ('TPS', 'TEPUS', ''),
  ('TRH', 'TERAH', ''),
  ('TRG', 'TERANG', ''),
  ('TRP', 'TERAP', ''),
  ('TKP', 'TERINGKAP', ''),
  ('TST', 'TERSAT', ''),
  ('TRS', 'TERAS', ''),
  ('TMN', 'TIMUN', ''),
  ('TYG', 'TOK YONG', ''),
  ('TKG', 'TONGKANG', ''),
  ('TUL(TUG)', 'TUALANG', ''),
  ('TGL', 'TUNGGAL', ''),
  ('ULR', 'ULAR', ''),
  ('UDG', 'ULU DONG', ''),
  ('UTM', 'ULU TIRAM', ''),
  ('WPU', 'WARPU', ''),
  ('WAU', 'WAU', ''),
  ('WNG', 'WENG', ''),
  ('YPG', 'YONG PENG', '');